package types

// Event types for the liquidity module.
const (
	EventTypeCreatePair       = "create_pair"
	EventTypeCreatePool       = "create_pool"
	EventTypeDepositBatch     = "deposit_batch"
	EventTypeWithdrawBatch    = "withdraw_batch"
	EventTypeLimitOrderBatch  = "limit_order_batch"
	EventTypeMarketOrderBatch = "market_order_batch"
	EventTypeCancelOrder      = "cancel_order"
	EventTypeDepositResult    = "deposit_result"
	EventTypeWithdrawalResult = "withdrawal_result"
	EventTypeOrderResult      = "order_result"

	AttributeKeyCreator            = "creator"
	AttributeKeyDepositor          = "depositor"
	AttributeKeyWithdrawer         = "withdrawer"
	AttributeKeyOrderer            = "orderer"
	AttributeKeyBaseCoinDenom      = "base_coin_denom"
	AttributeKeyQuoteCoinDenom     = "quote_coin_denom"
	AttributeKeyDepositCoins       = "deposit_coins"
	AttributeKeyAcceptedCoins      = "accepted_coins"
	AttributeKeyMintedPoolCoin     = "minted_pool_coin"
	AttributeKeyPoolCoin           = "pool_coin"
	AttributeKeyWithdrawnCoins     = "withdrawn_coins"
	AttributeKeyRefundedCoin       = "refunded_coin"
	AttributeKeyReserveAddress     = "reserve_address"
	AttributeKeyEscrowAddress      = "escrow_address"
	AttributeKeyRequestId          = "request_id"
	AttributeKeyPoolId             = "pool_id"
	AttributeKeyPairId             = "pair_id"
	AttributeKeyBatchId            = "batch_id"
	AttributeKeySwapRequestId      = "swap_request_id"
	AttributeKeySwapDirection      = "swap_direction"
	AttributeKeyOfferCoin          = "offer_coin"
	AttributeKeyDemandCoinDenom    = "demand_coin_denom"
	AttributeKeyPrice              = "price"
	AttributeKeyAmount             = "amount"
	AttributeKeyOpenAmount         = "open_amount"
	AttributeKeyExpireAt           = "expire_at"
	AttributeKeyRemainingOfferCoin = "remaining_offer_coin"
	AttributeKeyReceivedCoin       = "received_coin"
	AttributeKeyStatus             = "status"
)
