// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: crescent/exchange/v1beta1/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Params struct {
	MarketCreationFee github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=market_creation_fee,json=marketCreationFee,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"market_creation_fee"`
	Fees              Fees                                     `protobuf:"bytes,2,opt,name=fees,proto3" json:"fees"`
	MaxOrderLifespan  time.Duration                            `protobuf:"bytes,3,opt,name=max_order_lifespan,json=maxOrderLifespan,proto3,stdduration" json:"max_order_lifespan"`
	// max_order_price_ratio defines the ratio of the maximum possible order price compared to the market's last price
	MaxOrderPriceRatio      github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=max_order_price_ratio,json=maxOrderPriceRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"max_order_price_ratio"`
	DefaultMinOrderQuantity github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=default_min_order_quantity,json=defaultMinOrderQuantity,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"default_min_order_quantity"`
	DefaultMinOrderQuote    github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=default_min_order_quote,json=defaultMinOrderQuote,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"default_min_order_quote"`
	DefaultMaxOrderQuantity github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,7,opt,name=default_max_order_quantity,json=defaultMaxOrderQuantity,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"default_max_order_quantity"`
	DefaultMaxOrderQuote    github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,8,opt,name=default_max_order_quote,json=defaultMaxOrderQuote,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"default_max_order_quote"`
	MaxSwapRoutesLen        uint32                                 `protobuf:"varint,9,opt,name=max_swap_routes_len,json=maxSwapRoutesLen,proto3" json:"max_swap_routes_len,omitempty"`
	MaxNumMMOrders          uint32                                 `protobuf:"varint,10,opt,name=max_num_mm_orders,json=maxNumMmOrders,proto3" json:"max_num_mm_orders,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_194713c21235dedc, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type Fees struct {
	DefaultMakerFeeRate        github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=default_maker_fee_rate,json=defaultMakerFeeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"default_maker_fee_rate"`
	DefaultTakerFeeRate        github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=default_taker_fee_rate,json=defaultTakerFeeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"default_taker_fee_rate"`
	DefaultOrderSourceFeeRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=default_order_source_fee_ratio,json=defaultOrderSourceFeeRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"default_order_source_fee_ratio"`
}

func (m *Fees) Reset()         { *m = Fees{} }
func (m *Fees) String() string { return proto.CompactTextString(m) }
func (*Fees) ProtoMessage()    {}
func (*Fees) Descriptor() ([]byte, []int) {
	return fileDescriptor_194713c21235dedc, []int{1}
}
func (m *Fees) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fees) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fees.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fees) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fees.Merge(m, src)
}
func (m *Fees) XXX_Size() int {
	return m.Size()
}
func (m *Fees) XXX_DiscardUnknown() {
	xxx_messageInfo_Fees.DiscardUnknown(m)
}

var xxx_messageInfo_Fees proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "crescent.exchange.v1beta1.Params")
	proto.RegisterType((*Fees)(nil), "crescent.exchange.v1beta1.Fees")
}

func init() {
	proto.RegisterFile("crescent/exchange/v1beta1/params.proto", fileDescriptor_194713c21235dedc)
}

var fileDescriptor_194713c21235dedc = []byte{
	// 637 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xcf, 0x4f, 0xdb, 0x30,
	0x14, 0xc7, 0x1b, 0xe8, 0xf8, 0x61, 0x34, 0x34, 0x0c, 0x1b, 0x81, 0x43, 0x5a, 0x71, 0x40, 0xbd,
	0xe0, 0x0c, 0xa6, 0x49, 0xdb, 0x61, 0x97, 0x82, 0x90, 0x26, 0xd1, 0x0d, 0xc2, 0xb4, 0xc3, 0x2e,
	0x91, 0x9b, 0xbe, 0x96, 0xa8, 0xb5, 0x9d, 0xd9, 0x0e, 0x14, 0xed, 0x5f, 0xd8, 0x61, 0xc7, 0xfd,
	0x0d, 0xfb, 0x3b, 0x76, 0xe0, 0xc8, 0x71, 0xda, 0x01, 0xb6, 0xf2, 0x8f, 0x4c, 0x76, 0x92, 0xb6,
	0x68, 0x4c, 0x1a, 0x70, 0x4a, 0x1c, 0xbf, 0xf7, 0xfd, 0xf8, 0xfb, 0xf2, 0x9e, 0xd1, 0x7a, 0x24,
	0x41, 0x45, 0xc0, 0xb5, 0x0f, 0xfd, 0xe8, 0x88, 0xf2, 0x0e, 0xf8, 0xc7, 0x9b, 0x4d, 0xd0, 0x74,
	0xd3, 0x4f, 0xa8, 0xa4, 0x4c, 0x91, 0x44, 0x0a, 0x2d, 0xf0, 0x4a, 0x11, 0x47, 0x8a, 0x38, 0x92,
	0xc7, 0xad, 0x2e, 0x75, 0x44, 0x47, 0xd8, 0x28, 0xdf, 0xbc, 0x65, 0x09, 0xab, 0x5e, 0x47, 0x88,
	0x4e, 0x0f, 0x7c, 0xbb, 0x6a, 0xa6, 0x6d, 0xbf, 0x95, 0x4a, 0xaa, 0x63, 0xc1, 0x8b, 0xfd, 0x48,
	0x28, 0x26, 0x94, 0xdf, 0xa4, 0x6a, 0x84, 0x8c, 0x44, 0x9c, 0xef, 0xaf, 0x7d, 0x9e, 0x46, 0x53,
	0xfb, 0xf6, 0x04, 0xf8, 0x13, 0x5a, 0x64, 0x54, 0x76, 0x41, 0x87, 0x91, 0x04, 0xab, 0x11, 0xb6,
	0x01, 0x5c, 0xa7, 0x3a, 0x59, 0x9b, 0xdb, 0x5a, 0x21, 0x99, 0x10, 0x31, 0x42, 0xc5, 0x99, 0xc8,
	0xb6, 0x88, 0x79, 0xfd, 0xe9, 0xd9, 0x45, 0xa5, 0xf4, 0xed, 0xb2, 0x52, 0xeb, 0xc4, 0xfa, 0x28,
	0x6d, 0x92, 0x48, 0x30, 0x3f, 0xa7, 0x66, 0x8f, 0x0d, 0xd5, 0xea, 0xfa, 0xfa, 0x34, 0x01, 0x65,
	0x13, 0x54, 0xb0, 0x90, 0x71, 0xb6, 0x73, 0xcc, 0x2e, 0x00, 0x7e, 0x89, 0xca, 0x6d, 0x00, 0xe5,
	0x4e, 0x54, 0x9d, 0xda, 0xdc, 0x56, 0x85, 0xfc, 0xb3, 0x0e, 0x64, 0x17, 0x40, 0xd5, 0xcb, 0x86,
	0x19, 0xd8, 0x14, 0x7c, 0x80, 0x30, 0xa3, 0xfd, 0x50, 0xc8, 0x16, 0xc8, 0xb0, 0x17, 0xb7, 0x41,
	0x25, 0x94, 0xbb, 0x93, 0x56, 0x68, 0x85, 0x64, 0xf5, 0x21, 0x45, 0x7d, 0xc8, 0x4e, 0x5e, 0x9f,
	0xfa, 0x8c, 0x91, 0xf8, 0x7a, 0x59, 0x71, 0x82, 0x47, 0x8c, 0xf6, 0xdf, 0x9a, 0xec, 0xbd, 0x3c,
	0x19, 0x53, 0xf4, 0x78, 0x24, 0x99, 0xc8, 0x38, 0x82, 0xd0, 0x66, 0xb9, 0xe5, 0xaa, 0x53, 0x9b,
	0xad, 0x13, 0x93, 0xfa, 0xf3, 0xa2, 0xb2, 0xfe, 0x1f, 0x8e, 0x77, 0x20, 0x0a, 0x70, 0x01, 0xd8,
	0x37, 0x52, 0x81, 0x51, 0xc2, 0x5d, 0xb4, 0xda, 0x82, 0x36, 0x4d, 0x7b, 0x3a, 0x64, 0x31, 0xcf,
	0x51, 0x1f, 0x53, 0xca, 0x75, 0xac, 0x4f, 0xdd, 0x07, 0xb7, 0xe6, 0xbc, 0xe6, 0x3a, 0x58, 0xce,
	0x15, 0x1b, 0x31, 0xb7, 0xb8, 0x83, 0x5c, 0x0e, 0x03, 0x5a, 0xbe, 0x09, 0x26, 0x34, 0xb8, 0x53,
	0x77, 0x22, 0x2d, 0xfd, 0x45, 0x12, 0x1a, 0xae, 0x79, 0x1a, 0x96, 0x6f, 0xe8, 0x69, 0xfa, 0x7e,
	0x9e, 0xf2, 0x12, 0xde, 0xe8, 0x69, 0x0c, 0x66, 0x3c, 0xcd, 0xdc, 0xcf, 0xd3, 0x90, 0x64, 0x3c,
	0x6d, 0x98, 0xa9, 0xe8, 0x87, 0xea, 0x84, 0x26, 0xa1, 0x14, 0xa9, 0x06, 0x15, 0xf6, 0x80, 0xbb,
	0xb3, 0x55, 0xa7, 0xf6, 0xd0, 0x76, 0xce, 0xe1, 0x09, 0x4d, 0x02, 0xbb, 0xb1, 0x07, 0x1c, 0xbf,
	0x42, 0x0b, 0x26, 0x9c, 0xa7, 0x2c, 0x64, 0x2c, 0x3b, 0x94, 0x72, 0x91, 0x09, 0xae, 0xe3, 0xc1,
	0x45, 0x65, 0xbe, 0x41, 0xfb, 0x6f, 0x52, 0xd6, 0x68, 0x58, 0x82, 0x0a, 0xe6, 0x59, 0xb6, 0x66,
	0xd9, 0x7a, 0xed, 0xfb, 0x04, 0x2a, 0x9b, 0x06, 0xc7, 0x11, 0x7a, 0x32, 0x72, 0xd7, 0x05, 0x69,
	0x46, 0xd1, 0xf4, 0xa0, 0x99, 0xc7, 0xbb, 0xb4, 0xe0, 0xe2, 0xd0, 0x5c, 0x17, 0xe4, 0x2e, 0x98,
	0x26, 0x84, 0x71, 0x88, 0xbe, 0x0e, 0x99, 0xb8, 0x17, 0xe4, 0xdd, 0x38, 0x44, 0x22, 0xaf, 0x80,
	0x64, 0xff, 0x48, 0x89, 0x54, 0x46, 0x50, 0xb0, 0x62, 0x61, 0x47, 0xf5, 0xf6, 0xb0, 0xa2, 0xd5,
	0x6c, 0xe5, 0x0e, 0xad, 0x66, 0x86, 0x8c, 0x45, 0xfd, 0xfd, 0xd9, 0x6f, 0xaf, 0x74, 0x36, 0xf0,
	0x9c, 0xf3, 0x81, 0xe7, 0xfc, 0x1a, 0x78, 0xce, 0x97, 0x2b, 0xaf, 0x74, 0x7e, 0xe5, 0x95, 0x7e,
	0x5c, 0x79, 0xa5, 0x0f, 0x2f, 0xc6, 0x09, 0xf9, 0x3d, 0xb3, 0xc1, 0x41, 0x9f, 0x08, 0xd9, 0x1d,
	0x7e, 0xf0, 0x8f, 0x9f, 0xfb, 0xfd, 0xd1, 0x6d, 0x6d, 0xb9, 0xcd, 0x29, 0x7b, 0x8d, 0x3c, 0xfb,
	0x13, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xba, 0x53, 0xf3, 0xcf, 0x05, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxNumMMOrders != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxNumMMOrders))
		i--
		dAtA[i] = 0x50
	}
	if m.MaxSwapRoutesLen != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxSwapRoutesLen))
		i--
		dAtA[i] = 0x48
	}
	{
		size := m.DefaultMaxOrderQuote.Size()
		i -= size
		if _, err := m.DefaultMaxOrderQuote.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.DefaultMaxOrderQuantity.Size()
		i -= size
		if _, err := m.DefaultMaxOrderQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.DefaultMinOrderQuote.Size()
		i -= size
		if _, err := m.DefaultMinOrderQuote.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.DefaultMinOrderQuantity.Size()
		i -= size
		if _, err := m.DefaultMinOrderQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.MaxOrderPriceRatio.Size()
		i -= size
		if _, err := m.MaxOrderPriceRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.MaxOrderLifespan, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.MaxOrderLifespan):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Fees.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.MarketCreationFee) > 0 {
		for iNdEx := len(m.MarketCreationFee) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MarketCreationFee[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *Fees) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fees) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fees) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.DefaultOrderSourceFeeRatio.Size()
		i -= size
		if _, err := m.DefaultOrderSourceFeeRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.DefaultTakerFeeRate.Size()
		i -= size
		if _, err := m.DefaultTakerFeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.DefaultMakerFeeRate.Size()
		i -= size
		if _, err := m.DefaultMakerFeeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MarketCreationFee) > 0 {
		for _, e := range m.MarketCreationFee {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = m.Fees.Size()
	n += 1 + l + sovParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.MaxOrderLifespan)
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxOrderPriceRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DefaultMinOrderQuantity.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DefaultMinOrderQuote.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DefaultMaxOrderQuantity.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DefaultMaxOrderQuote.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.MaxSwapRoutesLen != 0 {
		n += 1 + sovParams(uint64(m.MaxSwapRoutesLen))
	}
	if m.MaxNumMMOrders != 0 {
		n += 1 + sovParams(uint64(m.MaxNumMMOrders))
	}
	return n
}

func (m *Fees) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DefaultMakerFeeRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DefaultTakerFeeRate.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.DefaultOrderSourceFeeRatio.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketCreationFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MarketCreationFee = append(m.MarketCreationFee, types.Coin{})
			if err := m.MarketCreationFee[len(m.MarketCreationFee)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fees", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Fees.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderLifespan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.MaxOrderLifespan, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOrderPriceRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxOrderPriceRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultMinOrderQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultMinOrderQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultMinOrderQuote", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultMinOrderQuote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultMaxOrderQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultMaxOrderQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultMaxOrderQuote", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultMaxOrderQuote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSwapRoutesLen", wireType)
			}
			m.MaxSwapRoutesLen = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxSwapRoutesLen |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxNumMMOrders", wireType)
			}
			m.MaxNumMMOrders = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxNumMMOrders |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fees) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fees: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fees: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultMakerFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultMakerFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultTakerFeeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultTakerFeeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultOrderSourceFeeRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DefaultOrderSourceFeeRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
